### ISSUE TITLE
ASTROPY_VERSION=stable not recognized in AppVeyor?

### ISSUE THREAD

**Issue by matteobachetti** [astropy/ci-helpers#10]
I have the following setup in my appveyor.yml:
```
  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
      CONDA_DEPENDENCIES: "scipy matplotlib"
      NUMPY_VERSION: "1.9.1"
      ASTROPY_VERSION: "stable"
```

AppVeyor exits with 
```
(...)
Fetching package metadata: ...... 
Error: No packages found in current win-64 channels matching: astropy stable*
 
You can search for this package on anaconda.org with
 
    anaconda search -t conda astropy stable*
 
You may need to install the anaconda-client command line client with
 
    conda install anaconda-client
 
 
SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
(...)
```
