### ISSUE TITLE
gitlab support 

### ISSUE THREAD

**Issue by kain88-de** [astropy/ci-helpers#260]
I toyed today with ci-helpers on a gitlab CI test runner. It was relatively straight forward to get the ci-helper script to run. Below is the job setting I used.

```yaml
job-name:
  image: debian:9
  stage: minimal
  variables:
    PYTHON_VERSION: "2.7"
    NUMPY_VERSION: "1.10.4"
    CONDA_DEPENDENCIES: 'mdanalysis pyyaml'
    CONDA_CHANNELS: "conda-forge"
  script:
    - apt-get update -y
    - apt-get install git wget bzip2 -y
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_linux.sh
    - python setup.py test
```

If there is interest I cal also look into writing some docs and adding it to ci-helpers officially. I assume this will also help to support circleci as they use images from dockerhub now as well.
