### ISSUE TITLE
Python 3.8 environments on travis hang

### ISSUE THREAD

**Issue by djhoese** [astropy/ci-helpers#456]
I just recently updated my travis to use python 3.8 and now the ci-helper's based conda install can't seem to get passed a certain installation step. From what I can tell it isn't related to the dependencies I'm installing.

Here is an example travis fail:

https://travis-ci.com/github/ssec/polar2grid/jobs/384028021

And the config:

<details>
```
language: generic
env:
  global:
    # Set defaults to avoid repeating in most cases
    - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
    - NUMPY_VERSION=stable
    - MAIN_CMD='python setup.py'
    - CONDA_DEPENDENCIES='xarray dask toolz Cython sphinx pillow matplotlib scipy pyyaml pyproj pyresample coveralls coverage codecov behave netcdf4 h5py h5netcdf gdal rasterio imageio pyhdf libtiff sphinx-argparse graphviz python-graphviz pycoast pytest zarr pylibtiff python-geotiepoints'
    - PIP_DEPENDENCIES='trollsift trollimage pyspectral pyorbital'
    - SETUP_XVFB=False
    - EVENT_TYPE='push pull_request'
    - SETUP_CMD='test'
    - CONDA_CHANNELS='conda-forge'
    - CONDA_CHANNEL_PRIORITY='strict'
matrix:
  include:
  - env: PYTHON_VERSION=3.8
    os: linux
  - env: PYTHON_VERSION=3.8
    os: osx
install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install --no-deps git+https://github.com/pytroll/satpy.git
  - pip install -e . --no-deps
script:
  - python -m polar2grid.tests && cd doc && make html
```
</details>

Normally I would think this is an unsolvable conda environment but seeing as it doesn't seem to be including my dependencies I can't understand why.
